### server
GET http://localhost:5000


### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "johndoe123"
}


### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "johndoe123"
}


### private route
GET http://localhost:5000/api/me/profile


### logout
DELETE  http://localhost:5000/api/auth/logout